
<div class="container">
    <div class="w-25 content mt-5">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi blanditiis dolor eligendi error est explicabo fugit, id ipsum laborum magni minus nemo obcaecati placeat possimus ratione sequi tenetur voluptas voluptatibus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut inventore iusto, molestias nemo pariatur quaerat quo sapiente! Asperiores assumenda debitis distinctio fuga illo numquam rem similique unde. Ad, autem, nihil. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci consequuntur dolore, fuga incidunt libero modi. Architecto blanditiis consequuntur culpa eaque, et ex harum libero omnis quisquam quo similique velit, voluptates? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad atque quo voluptas. Ad aut autem consequatur delectus deserunt eaque est, numquam possimus, qui quia reiciendis voluptas voluptatibus. Cum, illo iure! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto dolorum incidunt labore maiores officiis quasi quisquam quo sed sit tempore voluptates, voluptatibus voluptatum! Distinctio earum nostrum officiis rem sint velit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam debitis delectus ducimus error expedita fuga illum obcaecati quidem tempore voluptatum. Ab ad atque eaque fugit, natus perspiciatis quis vel voluptate? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias animi delectus dolores ducimus, et explicabo incidunt iusto labore molestias numquam placeat praesentium qui quidem quis rem ut velit vero vitae. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab earum error excepturi facere facilis fugit inventore laudantium modi molestiae natus, neque nihil nostrum perspiciatis quas qui quis sunt, veritatis, voluptatibus?
    </div>
</div>


{!! BBstyle($_this->path.DS.'css'.DS.'style.css',$_this) !!}
{!! BBscript($_this->path.DS.'js'.DS.'custom.js',$_this) !!}